USE [master]
GO
/****** Object:  Database [kddinev18]    Script Date: 14/11/2022 22:33:51 ******/
CREATE DATABASE [kddinev18]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'kddinev18', FILENAME = N'C:\Users\User\kddinev18.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'kddinev18_log', FILENAME = N'C:\Users\User\kddinev18_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [kddinev18].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [kddinev18] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [kddinev18] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [kddinev18] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [kddinev18] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [kddinev18] SET ARITHABORT OFF 
GO
ALTER DATABASE [kddinev18] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [kddinev18] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [kddinev18] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [kddinev18] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [kddinev18] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [kddinev18] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [kddinev18] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [kddinev18] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [kddinev18] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [kddinev18] SET  DISABLE_BROKER 
GO
ALTER DATABASE [kddinev18] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [kddinev18] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [kddinev18] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [kddinev18] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [kddinev18] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [kddinev18] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [kddinev18] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [kddinev18] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [kddinev18] SET  MULTI_USER 
GO
ALTER DATABASE [kddinev18] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [kddinev18] SET DB_CHAINING OFF 
GO
ALTER DATABASE [kddinev18] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [kddinev18] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [kddinev18] SET DELAYED_DURABILITY = DISABLED 
GO
USE [kddinev18]
GO
/****** Object:  Table [dbo].[Customers]    Script Date: 14/11/2022 22:33:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Customers](
	[Id] [int] NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[Address] [nvarchar](50) NOT NULL,
	[Email] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Customers] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Items]    Script Date: 14/11/2022 22:33:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Items](
	[Id] [int] NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[Type] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Items] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Repairs]    Script Date: 14/11/2022 22:33:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Repairs](
	[Id] [int] NOT NULL,
	[TechicianId] [int] NOT NULL,
	[ServiceId] [int] NOT NULL,
	[ItemId] [int] NOT NULL,
	[CustomerId] [int] NOT NULL,
	[From] [datetime2](3) NOT NULL,
	[DoneOn] [datetime2](3) NULL,
	[To] [datetime2](3) NOT NULL,
	[IsPickedUp] [bit] NOT NULL,
	[SatusId] [int] NOT NULL,
 CONSTRAINT [PK_Repairs] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Services]    Script Date: 14/11/2022 22:33:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Services](
	[Id] [int] NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[Price] [decimal](10, 2) NOT NULL,
 CONSTRAINT [PK_Services] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Statuses]    Script Date: 14/11/2022 22:33:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Statuses](
	[Id] [int] NOT NULL,
	[Status] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Statuses] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Technicians]    Script Date: 14/11/2022 22:33:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Technicians](
	[Id] [int] NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[Address] [nvarchar](50) NOT NULL,
	[Email] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Technicians] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Repairs]  WITH CHECK ADD  CONSTRAINT [FK_Repairs_Customers] FOREIGN KEY([CustomerId])
REFERENCES [dbo].[Customers] ([Id])
GO
ALTER TABLE [dbo].[Repairs] CHECK CONSTRAINT [FK_Repairs_Customers]
GO
ALTER TABLE [dbo].[Repairs]  WITH CHECK ADD  CONSTRAINT [FK_Repairs_Items] FOREIGN KEY([ItemId])
REFERENCES [dbo].[Items] ([Id])
GO
ALTER TABLE [dbo].[Repairs] CHECK CONSTRAINT [FK_Repairs_Items]
GO
ALTER TABLE [dbo].[Repairs]  WITH CHECK ADD  CONSTRAINT [FK_Repairs_Services] FOREIGN KEY([ServiceId])
REFERENCES [dbo].[Services] ([Id])
GO
ALTER TABLE [dbo].[Repairs] CHECK CONSTRAINT [FK_Repairs_Services]
GO
ALTER TABLE [dbo].[Repairs]  WITH CHECK ADD  CONSTRAINT [FK_Repairs_Statuses] FOREIGN KEY([SatusId])
REFERENCES [dbo].[Statuses] ([Id])
GO
ALTER TABLE [dbo].[Repairs] CHECK CONSTRAINT [FK_Repairs_Statuses]
GO
ALTER TABLE [dbo].[Repairs]  WITH CHECK ADD  CONSTRAINT [FK_Repairs_Technicians] FOREIGN KEY([TechicianId])
REFERENCES [dbo].[Technicians] ([Id])
GO
ALTER TABLE [dbo].[Repairs] CHECK CONSTRAINT [FK_Repairs_Technicians]
GO
USE [master]
GO
ALTER DATABASE [kddinev18] SET  READ_WRITE 
GO
