SELECT [Id]
      ,[TechicianId]
      ,[ServiceId]
      ,[ItemId]
      ,[CustomerId]
      ,[From]
      ,[DoneOn]
      ,[To]
      ,[IsPickedUp]
      ,[SatusId]
  FROM [kddinev18].[dbo].[Repairs]
  WHERE TechicianId = 1